### ISSUE TITLE
pokemon evolved doesnt appear in pokedex

### ISSUE THREAD

**Issue by magmion** [oliver-ni/poketwo#144] opened 2021-02-09 09:39 UTC
evolved a metapod but still says i have no butterfree although its there

**Comment by NathNathNathNath** [comment] 2021-02-09 09:40
@magmion 
This isn't a bug - it is intended behaviour :) Unlike the core series of games, you have to actually **catch** pokemon for them to be registered in your pokedex.

Evolving/trading/buying/getting from a box doesn't count

**Comment by magmion** [comment] 2021-02-09 09:46
alright. can we complete the pokedex tho?

**Comment by unknownking31** [comment] 2021-02-09 09:47
Yes because every pokemon can be caught 

> alright. can we complete the pokedex tho?

**Comment by magmion** [comment] 2021-02-09 09:48
thats cool! thanks for the quick response.

**Comment by NathNathNathNath** [comment] 2021-02-09 09:53
Yeah as @unknownking31 says, every pokemon will eventually spawn. Might take a long time (which is why only ~200 people hve completed their dex so far), but it is possible :) Good luck!

**Comment by cillosis** [comment] 2021-02-14 15:42
I have my dex complete and can confirm the only way to add new entries is to catch them. Even your starter pomemon won't count since it wasn't caught. Voting to close this as not a bug.

**Comment by oliver-ni** [comment] 2021-02-14 19:04
Closing for the reasons above :)

We *are* considering changing this behavior in the overhaul though (which is in progress).

**Closed** 2021-02-14 19:03 UTC
Labels: bug
